studentenhuisDS4/ds4reboot

ds4reboot/settings.py
eetlijst/views.py

Eetlijst hotfix

---

base/templates/home/quick_access.html

Added eetlijst button

---

.idea/.name
.idea/DS4 website.iml
.idea/dataSources.ids
.idea/dataSources.xml
.idea/dictionaries/Damien.xml
.idea/encodings.xml
.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
ds4reboot/settings.py

Reverts damienallen/ds4reboot#25
Merged into master. My mistake

Revert "Enable DBT"

---

eetlijst/views.py

Fixed date selection bug

---

base/templates/home/quick_access.html

Fix for eetlijst quick access form

---

bierlijst/management/commands/fine_eetlijst_balances.py
bierlijst/templates/bierlijst/boetes_log.html
bierlijst/templates/bierlijst/boetes_open.html
bierlijst/templates/bierlijst/boetes_options.html
bierlijst/views.py

Boetes improvements

---

eetlijst/views.py

Eetlijst costs fixed

---

eetlijst/templates/eetlijst/options.html
static/js/base.js

Removed date-submit. Added jquery event

---

base/templates/home/quick_access.html

Fix for closed eetlijst in quick access

---

eetlijst/templates/eetlijst/options.html

Add user's name to HO form on eetlijst

---

eetlijst/templates/eetlijst/signup_form.html

Cook disabled bg-color added

---

eetlijst/templates/eetlijst/table.html
eetlijst/views.py

Fixes #48 
You may want to integrate this into #44 instead of merging directly.

Allow users to edit costs

---

ds4admin/templates/ds4admin/balance.html
ds4admin/templates/ds4admin/housemates.html
ds4admin/templates/ds4admin/index.html
ds4admin/templates/ds4admin/permissions.html
ds4admin/urls.py
ds4admin/views.py

Also some formatting and reconfiguring of DS4admin pages.
Fixes #3

Added balance page to DSadmin

---

ds4admin/urls.py

Fixes #75.
Maybe we can involve Melle into pulling this :)

Fixed thesau/admin toggling

---

eetlijst/views.py

Waarschuwing bij allergie/dieet.

---

bierlijst/views.py

Voorkomt negatief biersaldo

---

eetlijst/templates/eetlijst/options.html
eetlijst/views.py

Fixes #73 and also orders dates of cost fill-in.

URL to day for cost. Order cost fill in by date.

---

thesau/views.py

Deleted function add-item

---

base/templates/home/quick_access.html
bierlijst/templates/bierlijst/table.html
bierlijst/views.py
static/js/base.js

Fixes #69 and tested bierlijst as well, because of replacing id's for medal+count selectors by class selectors. The reason for this is because there are 2 DOM's present (2x element), meaning an id-selector will only work on the first element found in the DOM.
(Two DOM's are present because of UI-kit's sizing approach (shadow DOM).)

Quick home ajax fix

---

bierlijst/views.py

White and red wine got same checks now.

---

bierlijst/templates/bierlijst/table.html
bierlijst/views.py

Fixes #87. Visual changes seem succesful and clear.

Slight template filling, styling and data insertion changes.

---

user/templates/user/profile_edit.html

Remove incorrect form validation option for current password.

Profile page password fix

---

bierlijst/views.py
static/js/base.js

Wine total was the wrong database number (total beer of user instead of just the sum of all active user their beer).
2nd fix, wine decimal was fixed to 0, which wasn't required.
3rd fix, admin was shown on beerlist
4th fix, improved wine not-whole error.

Fixed wine total and float decimal wine.

---

.gitignore
base/templates/base/nav.html
ds4admin/templates/ds4admin/index.html
ds4admin/templates/summary.html
ds4admin/templates/summary_options.html
ds4admin/urls.py
ds4admin/views.py
user/templates/user/profile_edit.html
user/views.py

Adds room number to profile page as well as house info to non-admin people.

Room number admin

---

user/views.py

Still I wonder if case insensitivity is better.

Double attempt at logging in. Lowercase as well as unchanged case.

---

static/js/base.js

Fixes #49 by conditional statement over update_medals() in base. It works, but is not flexible concerning path. Weird is that I cant call update_medals() in beerlist as a script.

Reduce medal requests
